---
  dataSource: "commits"
  prefix: ""
  onlyMilestones: false
  groupBy: {
    "New Features": ["feature"],
    "Enhancements": ["enhancement", "internal"],
    "Bug Fixes": ["bug"]
  }
  changelogFilename: "CHANGELOG.md"
